# PCA Codes

Putting some raw code examples from last quarter and from online regarding PCA. We got 3 options to try. I am leaning towards Option 3, but we should try all the options.

In [2]:
#importing packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.datasets import load_iris
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [3]:
"""
Import cleaned data here.

Hopefully in some format like this but in specific terms.

#reading the "features" csv
features=pd.read_csv('features.csv')
features.head()

#reading the "target" csv
target=pd.read_csv('target.csv')
target.head

"""

'\nImport cleaned data here.\n\nHopefully in some format like this but in specific terms.\n\n#reading the "features" csv\nfeatures=pd.read_csv(\'features.csv\')\nfeatures.head()\n\n#reading the "target" csv\ntarget=pd.read_csv(\'target.csv\')\ntarget.head\n\n'

## OPTION 1. Our Code from Final Project
Pretty much just ripping our code from the final project in using PCA analysis and right before we applied K-Means clustering. Not sure how effective this method is or exacly what we were doing or if it was even correct.

In [ ]:
#Create a PCA instance: pca
pca = PCA(n_components=2) #choose 8 because there 8 columns
#Fit the PCA instance to the scaled data
pca.fit(combdata)
#Transform the scaled data: pca_features
x_pca = pca.transform(combdata)
#Print the shape of pca_features
print(x_pca.shape)

In [ ]:
#Create a DataFrame from the PCA results
pca_df = pd.DataFrame(data = x_pca, columns = ['PC1', 'PC2'])
#Add the target variable to this dataframe
pca_df['Type of Material'] = combdata['Type of Material']
#Plot the first two principal components
plt.figure(figsize=(8,6))
sns.scatterplot(x='PC1', y='PC2', hue='Type of Material', data=pca_df, palette=['m', 'y', 'g'], alpha=0.6, s=100)
plt.title('PCA on Scaled Data')
plt.show()

## OPTION 2: Code from online that kind of does what we want
We probably want to do a feature importance after we find out which PC creates the largest variance. Putting a code from the internet that is similar to what we should want.
https://stackoverflow.com/questions/50796024/feature-variable-importance-after-a-pca-analysis

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
#In general a good idea is to scale the data
scaler = StandardScaler()
scaler.fit(X)
X=scaler.transform(X)    

pca = PCA()
x_new = pca.fit_transform(X)

def myplot(score,coeff,labels=None):
    xs = score[:,0]
    ys = score[:,1]
    n = coeff.shape[0]
    scalex = 1.0/(xs.max() - xs.min())
    scaley = 1.0/(ys.max() - ys.min())
    plt.scatter(xs * scalex,ys * scaley, c = y)
    for i in range(n):
        plt.arrow(0, 0, coeff[i,0], coeff[i,1],color = 'r',alpha = 0.5)
        if labels is None:
            plt.text(coeff[i,0]* 1.15, coeff[i,1] * 1.15, "Var"+str(i+1), color = 'g', ha = 'center', va = 'center')
        else:
            plt.text(coeff[i,0]* 1.15, coeff[i,1] * 1.15, labels[i], color = 'g', ha = 'center', va = 'center')
plt.xlim(-1,1)
plt.ylim(-1,1)
plt.xlabel("PC{}".format(1))
plt.ylabel("PC{}".format(2))
plt.grid()

#Call the function. Use only the 2 PCs.
myplot(x_new[:,0:2],np.transpose(pca.components_[0:2, :]))
plt.show()

In [ ]:
pca.explained_variance_ratio_
[0.72770452, 0.23030523, 0.03683832, 0.00515193]

In [ ]:
print(abs( pca.components_ ))

[[0.52237162 0.26335492 0.58125401 0.56561105]
 [0.37231836 0.92555649 0.02109478 0.06541577]
 [0.72101681 0.24203288 0.14089226 0.6338014 ]
 [0.26199559 0.12413481 0.80115427 0.52354627]]

In [ ]:
model = PCA(n_components=2).fit(train_features)
X_pc = model.transform(train_features)

# number of components
n_pcs= model.components_.shape[0]

# get the index of the most important feature on EACH component
# LIST COMPREHENSION HERE
most_important = [np.abs(model.components_[i]).argmax() for i in range(n_pcs)]

initial_feature_names = ['a','b','c','d','e']
# get the names
most_important_names = [initial_feature_names[most_important[i]] for i in range(n_pcs)]

# LIST COMPREHENSION HERE AGAIN
dic = {'PC{}'.format(i): most_important_names[i] for i in range(n_pcs)}

# build the dataframe
df = pd.DataFrame(dic.items())

## OPTION 3: Code from Dr. Sachi's Analysis mixed with our code 
Here is some code from Sachi, Lecture 20 plus our code from HW6. Pretty much Sachi trained a model with the PCA completed and then with the Random Forest, using a feature importance to find the most important feature. * This is the option I really want to try.

In [ ]:
# PCA 
from sklearn.decomposition import PCA 
# keep the first two components of the data 
pca = PCA (n_components=2)
# fit the PCA model to the scaled data 
pca.fit(scaled_df_standard)
x_pca = pca.transform(scaled_df_standard)
x_pca.shape

In [ ]:
plt.figure(figsize=(8,8))
scatter=plt.scatter(x_pca[:,0],x_pca[:,1],c =cancer.target)
plt.legend(handles=scatter.legend_elements()[0], labels=cancer.target_names.tolist(), title="diagnoses")
plt.xlabel("PC1")
plt.ylabel("PC2")

In [ ]:
# splitting the data into train and test 
X_train, X_test , y_train, y_test = train_test_split(cancer_df, cancer.target, test_size=0.20,random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
#applying PCA on the training data 
pca = PCA(n_components=4)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [ ]:
plt.figure(figsize=(8,8))
scatter=plt.scatter(X_train_pca[:,0],X_train_pca[:,1],c =y_train)
plt.legend(handles=scatter.legend_elements()[0], labels=cancer.target_names.tolist(), title="diagnoses")
plt.xlabel("PC1")
plt.ylabel("PC2")

In [ ]:
pca.explained_variance_ratio_

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF_clf = RandomForestClassifier(n_estimators=100, random_state=42)
RF_clf.fit(X_train_pca, y_train)

In [ ]:
print("Accuracy on training set: {:.3f}".format(RF_clf.score(X_train_pca, y_train)))
print("Accuracy on test set: {:.3f}".format(RF_clf.score(X_test_pca, y_test)))

And with that Random Forest Classifier, adding my own code to find Feature Importance

In [ ]:
feature_importances = RF_clf.feature_importances_
print(feature_importances)

In [ ]:
#Find the feature importance 
feature_importances_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': feature_importances
})
print(feature_importances_df.sort_values(by='Importance', ascending=False))